---

- name: Nginx public web - 404 template
  template: src=nginx/base_template_nginx_conf.j2 dest=/etc/nginx/404.html mode=0644
  tags:
    - publicweb
    - ctfserver

- name: Nginx public web - 404 template
  template: src=nginx/base_template_nginx_conf.j2 dest=/etc/nginx/404.html mode=0644
  tags:
    - publicweb
    - ctfserver


