---

# Enable multilib

- name: Add multilib to pacman
  lineinfile:
    dest: /etc/pacman.conf
    state: "present"
    line: "[multilib]"
    regexp: "^\\[multilib\\]"
    insertafter: "^#\\[multilib\\]"

- name: Add multilib (cont) to pacman
  lineinfile:
    dest: /etc/pacman.conf
    state: present
    line: "Include = /etc/pacman.d/mirrorlist"
    insertafter: "^\\[multilib\\]"
    regexp: "Include = /etc/pacman.d/mirrorlist"

- name: Install packages
  pacman: name={{ item }} update_cache=yes state=latest
  with_items:
# Nice OS packages to have
    - vim
    - tmux
    - extra/bash-completion
    - htop
    - whois
    - openssh
    - nmap
    - dnsutils
    - mlocate
    - bridge-utils

