---

- name: "Ensure the termrec(tty) logging directory for {{ ctfchroot }} exists"
  file:
    path: "{{ ctfchroot_bigbrother_log_dir }}"
    state: directory
    recurse: yes
    mode: 0777
  tags:
    - ctfserver
    - ctfbigbrother

