---

# This is needed to have a mountpoint for the levels to mount from host in newctfsession.sh
- name: "Chroot | Ensuring directory for {{ ctfchroot }} levels exists"
  file:
    state: directory
    owner: root
    group: root
    recurse: yes
    path: "{{ ctfchroot_playdir }}/levels"
    mode: 0755
  register: ctfchroot_dir_create
  tags:
    - ctfchroot
    - ctfserver

# Setup the ctfchroot directory
- name: "Chroot | Check if chroot for {{ ctfchroot }} is already bootstrapped."
  ignore_errors: True
  stat:
    path: "{{ ctfchroot_playdir }}/bin"
  register: ctfchroot_dir_already_bootstrapped
  tags:
    - ctfchroot
    - ctfserver

- name: "Chroot | Bootstrap chroot for {{ ctfchroot }} arch {{ ctfchroot_arch }}"
  command: "/usr/local/bin/arch-bootstrap.sh -r {{ ctfchroot_repo_url }} -a {{ ctfchroot_arch }} {{ ctfchroot_playdir }}"
  when:
    - ctfchroot_dir_already_bootstrapped.stat.exists is defined
    - ctfchroot_dir_already_bootstrapped.stat.exists == false
  register: ctfchroot_just_bootstrapped
  tags:
    - ctfchroot
    - ctfserver

- name: "Chroot | Copy {{ item }} from server to {{ ctfchroot_playdir }} arch {{ ctfchroot_arch }}"
  command: "/usr/bin/cp -rv {{ item }} {{ ctfchroot_playdir }}/{{ item }}"
  with_items:
    - "/etc/passwd"
    - "/etc/group"
    - "/etc/shadow"
    - "/etc/hostname"
    - "/etc/hosts"
  tags:
    - ctfchroot
    - ctfserver

- name: "Chroot | Copy tmux.conf from host to {{ ctfchroot }}"
  copy:
    remote_src: True
    src: /etc/tmux.conf
    dest: "{{ ctfchroot_playdir }}/etc/tmux.conf"
    owner: root
    group: root
    mode: 0644
  tags:
    - ctfchroot
    - ctfserver

- name: "Chroot | Set the correct mirrorlist file for pacman in {{ ctfchroot }}"
  template:
    src: chroot/mirrorlist.j2
    dest: "{{ ctfchroot_playdir }}/etc/pacman.d/mirrorlist"
    owner: root
    group: root
    mode: 0644
  tags:
    - ctfchroot
    - ctfserver

- name: "Chroot | Set the correct pacman.conf file in {{ ctfchroot }}"
  template:
    src: chroot/pacman.conf.j2
    dest: "{{ ctfchroot_playdir }}/etc/pacman.conf"
    owner: root
    group: root
    mode: 0644
  tags:
    - ctfchroot
    - ctfserver

- name: "Chroot | Setup locale.gen for {{ ctfchroot }}"
  copy:
    content: |
      # Locales
      en_US.UTF-8 UTF-8
      en_US ISO-8859-1
      no_NO.UTF-8 UTF-8
      no_NO ISO-8859-1
    dest: "{{ ctfchroot_playdir }}/etc/locale.gen"
    mode: 0644
  register: localegen_config_updated
  tags:
    - ctfchroot
    - ctfserver

- name: "Chroot | Setup locale.conf for {{ ctfchroot }}"
  template:
    src: chroot/locale.conf.j2
    dest: "{{ ctfchroot_playdir }}/etc/locale.conf"
  tags:
    - ctfchroot
    - ctfserver

- name: "Chroot | Setup vconsole.conf for {{ ctfchroot }}"
  template:
    src: chroot/vconsole.conf.j2
    dest: "{{ ctfchroot_playdir }}/etc/vconsole.conf"
  tags:
    - ctfchroot
    - ctfserver

- name: "Chroot | Setup bootstrap script for installation of base tools for {{ ctfchroot }}"
  # TODO: role:ctfserver:chroot - Cleanup hotfix with a better solution. Was done because of lack of time.
  ignore_errors: True
  copy:
    content: |
      #!/usr/bin/bash
      set -e -x
      #locale-gen
      pacman-key --init
      pacman-key --populate archlinux
      pacman -Sy --arch {{ ctfchroot_arch }}
      pacman --noconfirm --arch {{ ctfchroot_arch }} -v --force -S archlinux-keyring
      pacman -Sy --arch {{ ctfchroot_arch }}
      pacman --noconfirm --arch {{ ctfchroot_arch }} -v --force -S {{ ctfchroot_tools }}
      echo "Install done :)"
    dest: "{{ ctfchroot_playdir }}/bin/bootstrap-chroot.sh"
    mode: "0755"
  register: ctfchroot_bootstrap_script_installed
  when:
    - ctfchroot_dir_already_bootstrapped.stat.exists is defined
    - ctfchroot_dir_already_bootstrapped.stat.exists == false
  tags:
    - ctfchroot
    - ctfserver

- name: "Chroot | Running inner bootstrap script for {{ ctfchroot }}"
  # TODO: role:ctfserver:chroot - Cleanup hotfix with a better solution. Was done because of lack of time.
  ignore_errors: True
  when:
    - ctfchroot_bootstrap_script_installed is defined
    - ctfchroot_bootstrap_script_installed|succeeded
  command: "/usr/bin/arch-chroot {{ ctfchroot_playdir }} /bin/sh -c /bin/bootstrap-chroot.sh"
  register: ctfchroot_bootstrap_script_done
  tags:
    - ctfchroot
    - ctfserver

- name: "Chroot | Deleting bootstrap script for {{ ctfchroot }}"
  when: ctfchroot_bootstrap_script_done is defined
  file:
    state: absent
    path: "{{ ctfchroot_playdir }}/bin/bootstrap-chroot.sh"
  register: ctfchroot_bootstrap_done
  tags:
    - ctfchroot
    - ctfserver

- name: "Chroot | Removing unwanted binaries for {{ ctfchroot }}"
  file:
    state: absent
    path: "{{ ctfchroot_playdir }}{{ item }}"
  with_items:
# File system tools
    - "/usr/bin/fdisk"
    - "/usr/bin/mount"
    - "/usr/bin/umount"
    - "/usr/bin/swapon"
    - "/usr/bin/swapoff"
    - "/usr/bin/mkfs"
    - "/usr/bin/mkfs.cramfs"
    - "/usr/bin/wipefs"
# Priviliege escalation
    - "/usr/bin/sudo"
    - "/usr/bin/su"
    - "/usr/bin/passwd"
    - "/usr/bin/ksu"
    - "/usr/bin/kpasswd"
    - "/usr/bin/kadmin"
    - "/usr/bin/gpasswd"
    - "/usr/bin/chpasswd"
    - "/usr/bin/chgpasswd"
    - "/usr/bin/useradd"
    - "/usr/bin/usermod"
    - "/usr/bin/userdel"
    - "/usr/bin/groupadd"
    - "/usr/bin/groupmod"
    - "/usr/bin/groupdel"
    - "/usr/bin/newgrp"
    - "/usr/bin/unix_chkpwd"
    - "/usr/bin/unix_update"
# Arch linux stuff
    - "/usr/bin/makepkg"
    - "/usr/bin/makepkg-template"
# Information tools
    - "/usr/bin/dmesg"
    - "/usr/bin/last"
    - "/usr/bin/lastb"
    - "/usr/bin/lastlog"
    - "/usr/bin/lslocks"
    - "/usr/bin/losetup"
    - "/usr/bin/faillog"
    - "/usr/bin/lslogins"
    - "/usr/bin/lscpu"
    - "/usr/bin/lsipc"
# Kernel stuff
    - "/usr/bin/kmod"
    - "/usr/bin/mkswap"
    - "/usr/bin/mknod"
    - "/usr/bin/lsmod"
# Network stuff
    - "/usr/bin/xtables-multi"
    - "/usr/bin/xtables-compat-multi"
# Other stuff
    - "/usr/bin/checkupdates"
    - "/usr/bin/eject"
  tags:
    - ctfchroot
    - ctfserver
