---

## TODO: These shouldn't be allowed to fail, but because mounts will fuck up writable task, we can't execute them either.

# Setup the ctfchroot directory
- name: "CTF System Directories | Check 1/2 if CTF directories is created already."
  ignore_errors: True
  stat:
    path: "{{ ctfchroot_session_store_dir }}"
  register: ctf_sys_dir_store_exists
  tags:
    - ctfchroot
    - ctfserver

- name: "CTF System Directories | Check 2/2 if CTF directories is created already."
  ignore_errors: True
  stat:
    path: "{{ ctfbigbrother_log_dir }}"
  register: ctf_sys_dir_bigbrother_exists
  tags:
    - ctfchroot
    - ctfserver

- name: "CTF System Directories | Ensure CTF directories exists"
  ignore_errors: True
  when:
    - ctf_sys_dir_store_exists is not defined
    - ctf_sys_dir_bigbrother_exists is not defined
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
    mode: 0755
    owner: root
    group: "{{ default_ctfuser_group }}"
  register: ctfdirectories_installed
  with_items: "{{ ctf_datadir_directories_items }}"
  tags:
    - ctfserver
    - ctfsetup
    - ctflevels
    - ctflevelservice

- name: "CTF System Directories | Ensure CTF writable directories exists"
  ignore_errors: True
  when:
    - ctf_sys_dir_store_exists is defined
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
    mode: 0777
    owner: root
    group: "{{ default_ctfuser_group }}"
  register: ctfdirectories_installed_wr
  with_items: "{{ ctf_datadir_directories_items_wr }}"
  tags:
    - ctfserver
    - ctfsetup
    - ctflevels
    - ctflevelservice

- name: "CTF System Directories | Ensure CTF directories exists"
  when:
    - ctf_sys_dir_bigbrother_exists is defined
  debug:
    msg: "Set a register"
  register: ctfdirectories_installed

- name: "CTF System Directories | Ensure CTF writable directories exists"
  when:
    - ctf_sys_dir_store_exists is defined
  debug:
    msg: "Set a register"
  register: ctfdirectories_installed_wr

