---

- name: "Ensure the {{ item }} directory exists"
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
    mode: 0775
  register: ctfdirectories_installed
  with_items: "{{ ctf_datadir_directories_items }}"
  tags:
    - ctfserver
    - ctfsetup
    - ctflevels

