---

- name: Copy CTF banner
  template: src=banner.txt.j2 dest=/etc/banner.txt owner=root group=root mode=0644
  tags:
    - ctf
    - ctfserver
    - archlinux

- name: Basic CTF packages
  include: 'packages.yml'
  tags:
    - ctf
    - ctfserver
    - archlinux


- name: "Setup CTF Big Brother system"
  include: 'bigbrother.yml'
  tags:
    - ctf
    - ctfserver
    - ctfbigbrother
    - archlinux

- name: "Ensuring {{default_ctfuser_group}} group is available"
  become: yes
  become_user: root
  group:
    name: "{{default_ctfuser_group}}"
    state: present
  tags:
    - ctf
    - ctfserver
    - archlinux

- name: Including level setups
  become: yes
  become_user: root
  include: 'levels/main.yml'
  tags:
    - ctf
    - ctfserver
    - archlinux


- name: Including chroot setups
  become: yes
  become_user: root
  include: 'chroot.yml'
  tags:
    - ctf
    - ctfserver
    - ctfchroot
    - archlinux
