---

- name: Copy CTF banner
  template: src=banner.txt.j2 dest=/etc/banner.txt owner=root group=root mode=0644
  tags:
    - ctf
    - ctfserver
    - archlinux

- name: Basic CTF packages
  include: 'packages.yml'
  tags:
    - ctf
    - ctfserver
    - packages
    - archlinux

- name: Basic setup for sysctl
  include: 'sysctl.yml'
  tags:
    - ctf
    - ctfserver
    - sysctl
    - archlinux

- name: Setup shell environments
  include: 'shells/main.yml'
  tags:
    - ctf
    - ctfserver
    - archlinux

- name: "Setup CTF directory structure"
  include: 'ctfsetup.yml'
  tags:
    - ctf
    - ctfsetup
    - ctfserver

- name: "Setup CTF Big Brother system"
  include: 'bigbrother.yml'
  tags:
    - ctf
    - ctfserver
    - ctfbigbrother
    - ctfsystem

- name: "Ensuring {{ default_ctfuser_group }} group is available"
  become: yes
  become_user: root
  group:
    name: "{{ default_ctfuser_group }}"
    state: present
  tags:
    - ctf
    - ctfserver
    - archlinux

- name: Including level setups
  become: yes
  become_user: root
  include: 'levels/main.yml'
  tags:
    - ctf
    - ctfserver
    - ctfusers
    - archlinux
    - ctflevels

- name: Including chroot setups
  become: yes
  become_user: root
  include: 'chroot.yml'
  tags:
    - ctf
    - ctfserver
    - ctfchroot
    - archlinux

- name: Setting up security for the CTF game
  become: yes
  become_user: root
  include: 'security.yml'
  tags:
    - ctf
    - ctfserver
    - ctfsecurity
    - archlinux
