---

- name: "Basic CTF packages | Install packages"
  pacman: name={{ item }} update_cache=yes state=latest force=true
  with_items:
    - "{{ outer_item.packages }}"
  tags:
    - ctfserver
    - ctfpackages
    - archlinux
