---

- name: Make sure pacman cache and the system is up to date
  ignore_errors: True
  pacman:
    update_cache: yes
    upgrade: yes

- name: Install packages
  pacman: name={{ item }} update_cache=yes state=latest force=true
  with_items:
# Javascript tools
    - nodejs
    - npm
    - phantomjs
# Development, Debugging and Build Tools
    - strace
    - diffutils
    - gdb
    - binutils
    - patch
    - autoconf
    - automake
    - git
    - make
    - multilib-devel
    - abs
    - radare2
# File compress
    - zip
    - unzip
    - unrar
    - bzip2
    - gzip
    - tar
    - p7zip
# Python2 packages
    - python2
    - ipython2
    - python2-virtualenv
    - python2-pip
    - python2-jedi
# Python3
    - python
    - python-virtualenv
    - ipython
    - python-pip

