---

- name: Create CTF temporary directory
  file: path=/tmp/ctftmp state=directory mode=0777
  tags:
    - ctf1
    - ctfserver
    - ctflevels
    - ctfsecurity

- name: Adding configuration to /etc/sudoers.d/ctfusers
  template: src=sudo-ctfusers.j2 dest=/etc/sudoers.d/ctfusers owner=root group=root mode=0644
  tags:
    - ctf1
    - ctfserver
    - ctfsecurity
    - ctfloginsecurity

- name: Install /usr/bin/ctfmod-arch-chroot
  copy: src=ctfmod-arch-chroot.sh dest=/usr/bin/ctfmod-arch-chroot owner=root group=root mode=0755
  tags:
    - ctf1
    - ctfserver
    - ctfsecurity
    - ctfloginsecurity

- name: Install newctfsession.sh
  template: src=newctfsession.sh.j2 dest=/usr/local/bin/newctfsession.sh owner=root group=root mode=0755
  tags:
    - ctf1
    - ctfserver
    - ctfsecurity
    - ctfloginsecurity

- name: Install ctfssh-wrapper.sh
  template: src=ctfssh-wrapper.sh.j2 dest=/usr/local/bin/ctfssh-wrapper.sh owner=root group=root mode=0755
  tags:
    - ctf1
    - ctfserver
    - ctfsecurity
    - ctfloginsecurity

- name: Copy the preconfigured sshd_config
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0440
    validate: '/usr/sbin/sshd -t -f %s'
  notify: restart_sshd
  tags:
    - ctf1
    - ctfserver
    - ctfsecurity
    - ctfloginsecurity

