---

default_ctfuser_group: ctfusers

common_locale: 'en_US.UTF-8'
common_lang: 'en'

host_pinned_packages: 'linux linux-docs linux-headers'

## Bellow is CTF config

# Levels config

ctfgame_userlevels_enabled:
  - name: "Level 00"
    user: "level00"
    pwclean: "89lka3ur9sd2"
    groups: "level00,{{default_ctfuser_group}}"
    password: "$6$RWc.Gc5LvtTTZ9vw$fQ2xxIaOUtuP6WkZd.CRfyRKeCALyBBYskIZR/eHjUdjnJvdhz.aONcYQdanfVJqBXX4wYE5huUm1M.wgUURg/"
    suidowner: "level01"
    service: true
    binary: false


# Base directory config

ctf_datadir_directories_itemsw:
  - "/var/ctfgame1/tmp/sessions"
  - "/var/ctfgame1/sessions"
  - "/var/ctfgame1/services"
  - "/var/ctfgame1/libexec/shared"
  - "/var/ctfgame1/libexec/levels"
  - "/var/ctfgame1/bin"

ctf_tmp_datadir: '/var/ctfgame1/tmp'
ctf_libexec_dir: '/var/ctfgame1/libexec'
ctf_binary_dir:  '/var/ctfgame1/bin'
ctfbigbrother_log_dir: '/var/ctfgame1/bigbrother/termlog'


# Chroot directory config
ctfchroot_datadir: '/var/ctfgame1'
ctfchroot_playdir: '/ctf1chroot1'

## Bellow is config for the base chroot environment

ctfchroot: ctf1chroot1
ctfchroot_arch: i686
ctfchroot_tools: 'libcap ruby netcat man git which man-db man-pages python2 ipython2 tmux python ipython nodejs npm gdb gcc binutils radare2 tar unzip unrar go vim nano zsh bash nmap'
ctfchroot_repo_url: 'http://mirror.archlinux.no/'

# TODO: Move all directories relative to datadir above.
ctfchroot_shell_ohmyzsh_path: '/usr/share/ohmyzsh'


ctfchroot_session_store_dir: '/var/ctfgame1/sessions'

# Max sessions from same IP
ssh_max_sessions_from_same_ip: 100

# NOTE: This needs to be high numbers cause of the whole login process consumes a LOT.
# /etc/security/limits.conf parameters
ctfuser_max_open_files_soft: 65535
ctfuser_max_open_files_hard: 65535
