---

default_ctfuser_group: ctfusers

common_locale: 'en_US.UTF-8'
common_lang: 'en'



ctfchroot: ctf1chroot1
ctfchroot_arch: i686
ctfchroot_tools: 'libcap ruby netcat man git which man-db man-pages python2 ipython2 tmux python ipython nodejs npm gdb gcc binutils radare2 tar unzip unrar go vim nano zsh bash nmap'
ctfchroot_repo_url: 'http://mirror.archlinux.no/'

# Chroot directory config
ctfchroot_datadir: '/var/ctfgame1'
ctfchroot_playdir: '/ctf1chroot1'

# TODO: Move all directories relative to datadir above.
ctfchroot_bigbrother_log_dir: '/var/ctfgame1/bigbrother/termlog'
ctfchroot_shell_ohmyzsh_path: '/usr/share/ohmyzsh'
ctfchroot_control_items:
  - "/var/ctfgame1/tmp/sessions"
  - "/var/ctfgame1/sessions"
  - "/var/ctfgame1/services"
  - "/var/ctfgame1/libexec/shared"
  - "/var/ctfgame1/libexec/levelspesific"

ctfchroot_session_store_dir: '/var/ctfgame1/sessions'

# Max sessions from same IP
ssh_max_sessions_from_same_ip: 100

# NOTE: This needs to be high numbers cause of the whole login process consumes a LOT.
# /etc/security/limits.conf parameters
ctfuser_max_open_files_soft: 65535
ctfuser_max_open_files_hard: 65535
