---

# CTF Stuff
default_ctfuser_group: ctfusers

ctfchroot: ctf1chroot1
ctfchroot_arch: i686
ctfchroot_tools: 'python2 ipython2 tmux python ipython nodejs npm gdb gcc binutils radare2 tar unzip unrar go vim nano zsh bash nmap'
