---

# CTF Stuff
default_ctfuser_group: ctfusers

ctfchroot: ctf1chroot1
ctfchroot_arch: i686
ctfchroot_tools: 'libcap ruby netcat man git which man-db man-pages python2 ipython2 tmux python ipython nodejs npm gdb gcc binutils openssl radare2 tar unzip unrar go vim nano zsh bash nmap'


# Password encrypt howto:
#
# Linux:
#   mkpasswd --method=sha-512
#
# OS X and such:
#   pip install passlib
#   python -c "from passlib.hash import sha512_crypt; import getpass; print sha512_crypt.using(rounds=5000).hash(getpass.getpass())"
#

# TODO: Can we automate the password generation and return a password file after the playbook run?

#
# user: level00 password: 89lka3ur9sd2
# user: level01 password: fYIAv1NfRvEwJMcVPyJX
# user: level02 password: 8Ja2HNPzRNbsJcUuc6uV
# user: level03 password: 64nBQaf0lAwthCXgHVci
# user: level04 password: lbJa9HZFkPyO7pNJGDNJ
#

ctfgame_userlevels_enabled:
# TODO: If this works, convert all to more readable format.
  - name: "Level 00"
    user: "level00"
    pwclean: "89lka3ur9sd2"
    groups: "level00,{{default_ctfuser_group}}"
    password: "$6$RWc.Gc5LvtTTZ9vw$fQ2xxIaOUtuP6WkZd.CRfyRKeCALyBBYskIZR/eHjUdjnJvdhz.aONcYQdanfVJqBXX4wYE5huUm1M.wgUURg/"
  - name: "Level 01"
    user: "level01"
    pwclean: "fYIAv1NfRvEwJMcVPyJX"
    groups: "level00,level01,{{default_ctfuser_group}}"
    password: "$6$IIs.nwMlPioB38ge$V.L8M0hKSWu0a7FWpk3hUP7g0uN.gUYha8z2NyW3x.NKy4kIKNOo8VMN.dKo86au0xtruBJ6N.oCeYeuJTnpQ0"
  - name: "Level 02"
    user: "level02"
    pwclean: "8Ja2HNPzRNbsJcUuc6uV"
    groups: "level00,level01,level02,{{default_ctfuser_group}}"
    password: "$6$gnVQD5jXEvssG2IS$cocg/23RnDhgGpKMLODS.0LpqnSlPFFqFxBnCXasVU0uJZKywst5Dh5J13mK7/WDvLohZx7praHcda.ool0Fp/"
  - name: "Level 03"
    user: "level03"
    pwclean: "64nBQaf0lAwthCXgHVci"
    groups: "level00,level01,level02,level03,{{default_ctfuser_group}}"
    password: "$6$li5iFTDKRH1YEh6G$kBFtlEFHLQ2uSHapqhXAtzyWd.WgysogdwNJtATjp/K9Ld6.Qz4CmV6bEH.GhteZLU8vy1P5d10UPFk4zohFm0"
  - name: "Level 04"
    user: "level04"
    pwclean: "lbJa9HZFkPyO7pNJGDNJ"
    groups: "level00,level01,level02,level03,level04,{{default_ctfuser_group}}"
    password: "$6$PQrSxJGRpVLEvp59$9LWLgpsh4FffiT3XFLct.Zw2hp3SZsZAi8DbucQQbYKQWqlDVF1nPn5ptiL0fOA2f/HXueDewo2Jzud11GDyi0"

# TODO: Find a way to not repeat yourself? (Ref. above) :)
ctfgame_userlevels_extra:
  - { name: "Level 00", user: "level00", suidowner: "level01", service: true, binary: false }
  - { name: "Level 01", user: "level01", suidowner: "level02", service: false, binary: true }
  - { name: "Level 02", user: "level02", suidowner: "level03", service: false, binary: true }
  - { name: "Level 03", user: "level03", suidowner: "level04", service: false, binary: true }
  - { name: "Level 04", user: "level04", suidowner: "level04", service: false, binary: true }

