---

# CTF Stuff
default_ctfuser_group: ctfusers

ctfchroot: ctf1chroot1
ctfchroot_arch: i686
ctfchroot_tools: 'libcap ruby netcat man git which man-db man-pages python2 ipython2 tmux python ipython nodejs npm gdb gcc binutils openssl radare2 tar unzip unrar go vim nano zsh bash nmap'
