---

# CTF Stuff
default_ctfuser_group: ctfusers

ctfchroot: ctf1chroot1
ctfchroot_arch: i686
ctfchroot_tools: 'strace ltrace libcap ruby netcat man git which man-db man-pages python2 ipython2 tmux python ipython nodejs npm gdb gcc binutils openssl radare2 tar unzip unrar go vim nano zsh bash nmap'


# Password encrypt howto:
#
# Linux:
#   mkpasswd --method=sha-512
#
# OS X and such:
#   pip install passlib
#   python -c "from passlib.hash import sha512_crypt; import getpass; print sha512_crypt.using(rounds=5000).hash(getpass.getpass())"
#

# TODO: Can we automate the password generation and return a password file after the playbook run?

#
# user: level00 password: 89lka3ur9sd2
# user: level01 password: fYIAv1NfRvEwJMcVPyJX
# user: level02 password: 8Ja2HNPzRNbsJcUuc6uV
# user: level03 password: 64nBQaf0lAwthCXgHVci
# user: level04 password: lbJa9HZFkPyO7pNJGDNJ
# user: level05 password: RWUU5jtmNfRH7lWniQsu
# user: level06 password: OoXm8veaa9LcflE98lZf
# user: level07 password: UB0zX0Nj8GDAJuqLVCL1
#

ctfgame_userlevels_enabled:
  - name: "Level 00"
    user: "level00"
    pwclean: "89lka3ur9sd2"
    groups: "level00,{{default_ctfuser_group}}"
    password: "$6$RWc.Gc5LvtTTZ9vw$fQ2xxIaOUtuP6WkZd.CRfyRKeCALyBBYskIZR/eHjUdjnJvdhz.aONcYQdanfVJqBXX4wYE5huUm1M.wgUURg/"
    suidowner: "level01"
    suidenabled: False
    service: True
    binary: False
    extra_help: True
    binary_keep_source: False
    services:
      - "browser"
      - "webserver"
  - name: "Level 01"
    user: "level01"
    pwclean: "fYIAv1NfRvEwJMcVPyJX"
    groups: "level00,level01,{{default_ctfuser_group}}"
    password: "$6$IIs.nwMlPioB38ge$V.L8M0hKSWu0a7FWpk3hUP7g0uN.gUYha8z2NyW3x.NKy4kIKNOo8VMN.dKo86au0xtruBJ6N.oCeYeuJTnpQ0"
    suidowner: "level02"
    suidenabled: True
    service: False
    binary: True
    extra_help: False
    binary_keep_source: False
  - name: "Level 02"
    user: "level02"
    pwclean: "8Ja2HNPzRNbsJcUuc6uV"
    groups: "level00,level01,level02,{{default_ctfuser_group}}"
    password: "$6$gnVQD5jXEvssG2IS$cocg/23RnDhgGpKMLODS.0LpqnSlPFFqFxBnCXasVU0uJZKywst5Dh5J13mK7/WDvLohZx7praHcda.ool0Fp/"
    suidowner: "level03"
    suidenabled: True
    service: False
    binary: True
    extra_help: False
    binary_keep_source: False
  - name: "Level 03"
    user: "level03"
    pwclean: "64nBQaf0lAwthCXgHVci"
    groups: "level00,level01,level02,level03,{{default_ctfuser_group}}"
    password: "$6$li5iFTDKRH1YEh6G$kBFtlEFHLQ2uSHapqhXAtzyWd.WgysogdwNJtATjp/K9Ld6.Qz4CmV6bEH.GhteZLU8vy1P5d10UPFk4zohFm0"
    suidowner: "level04"
    suidenabled: True
    service: False
    binary: True
    extra_help: False
    binary_keep_source: False
  - name: "Level 04"
    user: "level04"
    pwclean: "lbJa9HZFkPyO7pNJGDNJ"
    groups: "level00,level01,level02,level03,level04,{{default_ctfuser_group}}"
    password: "$6$PQrSxJGRpVLEvp59$9LWLgpsh4FffiT3XFLct.Zw2hp3SZsZAi8DbucQQbYKQWqlDVF1nPn5ptiL0fOA2f/HXueDewo2Jzud11GDyi0"
    suidowner: "level05"
    suidenabled: True
    service: False
    binary: True
    extra_help: False
    binary_keep_source: True
  - name: "Level 05"
    user: "level05"
    pwclean: "RWUU5jtmNfRH7lWniQsu"
    groups: "level00,level01,level02,level03,level04,level05,{{default_ctfuser_group}}"
    password: "$6$WwqrV.QFs7rmvcxI$T4oiE9jF6V0U/8JMjxpR/qjPzo3ows.Xbs0wugvzjTlS7V.4djpXkl1hL.foFL9nTnTs.ii9x1DLQ.aZQ2g1Q0"
    suidowner: "level06"
    suidenabled: True
    service: False
    binary: True
    extra_help: False
    binary_keep_source: True
  - name: "Level 06"
    user: "level06"
    pwclean: "OoXm8veaa9LcflE98lZf"
    groups: "level00,level01,level02,level03,level04,level05,level06,{{default_ctfuser_group}}"
    password: "$6$DBmly86SYdmfhGv8$zrE49sLPZb.xSk/KRD5NJ52.IfNIa1sNQoU1gFcVX9n7WA9ImuAF6BqyiXLDvYZSo0z20B9sJvrdwbj4IbjII/"
    suidowner: "level07"
    suidenabled: True
    service: False
    binary: True
    extra_help: False
    binary_keep_source: True
  - name: "Level 07"
    user: "level07"
    pwclean: "UB0zX0Nj8GDAJuqLVCL1"
    groups: "level00,level01,level02,level03,level04,level05,level06,{{default_ctfuser_group}}"
    password: "$6$SgZhKBUEKaEtJUUP$J4cQ4.7brnRhNkbFJqz5/q9JKEx4Tu5ZlH24BPJmSx9Av2HNPHNEDGI/hzj/yaeC6Vs4S.zm9mDz8.doSBuGh/"
    suidowner: "level08"
    suidenabled: False
    service: False
    binary: False
    extra_help: False
    binary_keep_source: True



public_vhosts:
  - name: knowitctf
    config:
      nginx_main_domain: 'hackme.knowit.no'
      nginx_server_name: 'hackme.knowit.no www.hackme.knowit.no'
      nginx_ssl_listen_host: '0.0.0.0'
      nginx_ssl_listen_port: 443
      nginx_listen_host: '0.0.0.0'
      nginx_listen_port: 80
      nginx_allow_full_http: False
      nginx_enable_ssl: False
      nginx_ssl_certificate: ''
      nginx_ssl_certificate_key: ''
      nginx_enable_ssl_dhparam: False
      nginx_enable_ssl_dhparam_file: '/etc/nginx/ssl/dhparam.pem'
  - name: ctf1
    config:
      nginx_main_domain: 'ctf1.greyhat.no'
      nginx_server_name: 'ctf1.greyhat.no www.ctf1.greyhat.no'
      nginx_ssl_listen_host: '0.0.0.0'
      nginx_ssl_listen_port: 443
      nginx_listen_host: '0.0.0.0'
      nginx_listen_port: 80
      nginx_allow_full_http: False
      nginx_enable_ssl: False
      nginx_ssl_certificate: ''
      nginx_ssl_certificate_key: ''
      nginx_enable_ssl_dhparam: False
      nginx_enable_ssl_dhparam_file: '/etc/nginx/ssl/dhparam.pem'



