---

- name: "Level Home Setup | Does the iwashere.txt exists?"
  ignore_errors: True
  stat:
    path: "/home/{{item.user}}/iwashere.txt"
  register: iwashere_exists
  tags:
    - ctfchroot
    - ctfserver

- name: "Level Home Setup | Copy the iwashere.txt file for {{ item.name }} and set chattr +a to it"
  ignore_errors: True
  when:
    - iwashere_exists is not defined
  copy:
    src: iwashere.txt
    dest: "/home/{{item.user}}/iwashere.txt"
    owner: root
    group: "{{item.user}}"
    mode: 0660
    attributes: 'a'
  tags:
    - ctflevels
    - ctfhomes

- name: "Level Home Setup | Setup the .passwd file for {{ item.name }}"
  copy: content={{item.pwclean}} dest=/home/{{item.user}}/.passwd owner={{item.user}} group={{item.user}} mode=0440
  tags:
    - ctflevels
    - ctfhomes

- name: "Level Home Setup | Install help_its_hard.txt file for {{ item.name }}"
  ignore_errors: True
  when:
    - item.extra_help == True
  copy:
    src: "levels/{{item.user}}/help_its_hard.txt"
    dest: "/home/{{item.user}}/help_its_hard.txt"
    owner: root
    group: "{{item.user}}"
    mode: 0440
  tags:
    - ctflevels
    - ctfhomes

- name: "Level Home Setup | Copy the .profile for {{ item.name }}"
  template: src=dotprofile.j2 dest=/home/{{item.user}}/.profile owner={{item.user}} group={{item.user}} mode=0440
  tags:
    - ctflevels
    - ctfhomes

- name: "Level Home Setup | Copy the template for story.txt for {{ item.name }}"
  template:
    src: "levels/{{ item.user }}/story.txt.j2"
    dest: "/home/{{ item.user }}/story.txt"
    owner: root
    group: "{{ item.user }}"
    mode: 0440
  tags:
    - ctflevels
    - ctfhomes

- name: "Level Home Setup | Copy the recap.txt for {{ item.name }}"
  copy:
    src: "levels/{{ item.user }}/recap.txt"
    dest: "/home/{{ item.user }}/recap.txt"
    owner: root
    group: "{{ item.user }}"
    mode: 0440
  tags:
    - ctflevels
    - ctfhomes

- name: "Level Home Setup | Copy the .zshrc for {{ item.name }}"
  template: src=dotzshrc.j2 dest=/home/{{item.user}}/.zshrc owner=root group={{item.user}} mode=0440
  tags:
    - ctflevels
    - ctfhomes

- name: "Level Home Setup | Copy the .bashrc for {{ item.name }}"
  template: src=dotbashrc.j2 dest=/home/{{item.user}}/.bashrc owner=root group={{item.user}} mode=0440
  tags:
    - ctflevels
    - ctfhomes

- name: "Level Home Setup | Lock down the home directory for {{ item.name }}"
  file: path=/home/{{item.user}} state=directory owner=root group={{item.user}} mode=0750
  tags:
    - ctflevels
    - ctfhomes
