---


- name: "Adding group for {{ item.name }}"
  become: yes
  become_user: root
  group:
    name: "{{ item.user }}"
    state: present
  tags:
    - ctf1
    - ctfserver
    - ctflevels

- name: "Adding user for {{ item.name }}"
  become: yes
  become_user: root
  user:
    comment: "{{ item.name }}"
    name: "{{ item.user }}"
    password: "{{ item.password }}"
    state: present
    createhome: yes
    shell: /usr/bin/zsh
    update_password: always
    groups: "{{ item.groups }},{{ default_ctfuser_group }}"
    append: yes
  tags:
    - ctf1
    - ctfserver
    - ctflevels

- name: "Set softlimit settings for {{ item.name }} in /etc/security/limits.conf"
  pam_limits:
    domain: "{{ item.name }}"
    limit_type: soft
    limit_item: nofile
    value: "{{ ctfuser_max_open_files_soft }}"
  tags:
    - ctf1
    - ctfserver
    - ctflevels

- name: "Set hardlimit settings for {{ item.name }} in /etc/security/limits.conf"
  pam_limits:
    domain: "{{ item.name }}"
    limit_type: hard
    limit_item: nofile
    value: "{{ ctfuser_max_open_files_hard }}"
  tags:
    - ctf1
    - ctfserver
    - ctflevels

- name: "Copy the motd.txt for {{ item.name }}"
  template: src=motd.txt.j2 dest=/home/{{item.user}}/motd.txt owner={{item.user}} group={{item.user}} mode=0440
  tags:
    - ctf1
    - ctfserver
    - ctflevels

- name: "Copy the iwashere.txt file for {{ item.name }} and set chattr +a to it"
  copy:
    src: iwashere.txt
    dest: "/home/{{item.user}}/iwashere.txt"
    owner: root
    group: "{{item.user}}"
    mode: 0660
    attributes: '+a'
  tags:
    - ctf1
    - ctfserver
    - ctflevels

- name: "Setup the .passwd file for {{ item.name }}"
  copy: content={{item.pwclean}} dest=/home/{{item.user}}/.passwd owner={{item.user}} group={{item.user}} mode=0440
  tags:
    - ctf1
    - ctfserver
    - ctflevels

- name: "Copy the .profile for {{ item.name }}"
  template: src=dotprofile.j2 dest=/home/{{item.user}}/.profile owner={{item.user}} group={{item.user}} mode=0440
  tags:
    - ctf1
    - ctfserver
    - ctflevels

- name: "Copy the template for story.txt for {{ item.name }}"
  ignore_errors: True
  template:
    src: "levels/{{ item.user }}/story.txt.j2"
    dest: "/home/{{ item.user }}/story.txt"
    owner: "{{ item.user }}"
    group: "{{ item.user }}"
    mode: 0440
  tags:
    - ctf1
    - ctfserver
    - ctflevels

- name: "Copy the recap.txt for {{ item.name }}"
  ignore_errors: True
  copy:
    src: "levels/{{ item.user }}/recap.txt"
    dest: "/home/{{ item.user }}/recap.txt"
    owner: "{{ item.user }}"
    group: "{{ item.user }}"
    mode: 0440
  tags:
    - ctf1
    - ctfserver
    - ctflevels


- name: "Copy the .zshrc for {{ item.name }}"
  template: src=dotzshrc.j2 dest=/home/{{item.user}}/.zshrc owner={{item.user}} group={{item.user}} mode=0440
  tags:
    - ctf1
    - ctfserver
    - ctflevels


- name: "Copy the .bashrc for {{ item.name }}"
  template: src=dotbashrc.j2 dest=/home/{{item.user}}/.bashrc owner={{item.user}} group={{item.user}} mode=0440
  tags:
    - ctf1
    - ctfserver
    - ctflevels

- name: "Create task directory for {{ item.name }}"
  file: path=/levels/{{item.user}} state=directory owner={{item.user}} group={{item.user}} mode=0550
  tags:
    - ctf1
    - ctfserver
    - ctflevels


- name: "Lock down the home directory for {{ item.name }}"
  file: path=/home/{{item.user}} state=directory owner={{item.user}} group={{item.user}} mode=0550
  tags:
    - ctf1
    - ctfserver
    - ctflevels
