---

- name: "Adding group for {{ item.name }}"
  become: yes
  become_user: root
  group:
    name: "{{ item.user }}"
    state: present
  tags:
    - ctfserver
    - ctflevels

- name: "Adding user for {{ item.name }}"
  become: yes
  become_user: root
  user:
    comment: "{{ item.name }}"
    name: "{{ item.user }}"
    password: "{{ item.password }}"
    state: present
    createhome: yes
    shell: /usr/bin/zsh
    update_password: always
    groups: "{{ item.groups }},{{ default_ctfuser_group }}"
    append: yes
  tags:
    - ctfserver
    - ctflevels

- name: "Set softlimit settings for {{ item.name }} in /etc/security/limits.conf"
  pam_limits:
    domain: "{{ item.name }}"
    limit_type: soft
    limit_item: nofile
    value: "{{ ctfuser_max_open_files_soft }}"
  tags:
    - ctfserver
    - ctflevels

- name: "Set hardlimit settings for {{ item.name }} in /etc/security/limits.conf"
  pam_limits:
    domain: "{{ item.name }}"
    limit_type: hard
    limit_item: nofile
    value: "{{ ctfuser_max_open_files_hard }}"
  tags:
    - ctfserver
    - ctflevels

- name: "Create task directory for {{ item.name }}"
  file: path=/levels/{{item.user}} state=directory owner=root group={{item.user}} mode=0550
  tags:
    - ctfserver
    - ctflevels

- name: "Setup service for {{ item.name }}"
  file:
    path: "{{ ctf_libexec_dir }}/levels/{{ item.user }}"
    directory_mode: yes
    owner: root
    group: root
    mode: 0755
  when:
    - item.service == True
  tags:
    - ctfserver
    - ctflevels

- name: "Create ttyrec directory for {{ item.name }}"
  file:
    path: "{{ ctfchroot_session_store_dir }}/levels/{{ item.user }}"
    state: directory
    recurse: yes
    owner: root
    group: "{{item.user}}"
    mode: 0770
  tags:
    - ctfbigbrother
    - ctfserver
    - ctflevels

- name: "Setup home directory and related for {{ item.name }}"
  include: 'home.yml'
  tags:
    - ctflevels
    - ctfhomes
