---

- name: Create levels directory
  file: path=/levels state=directory mode=0755
  tags:
    - ctf1
    - ctfserver
    - ctflevels

- name: "Setting up CTF Levels and users"
  include: 'level_setup.yml'
  with_items:
    - "{{ ctfgame_userlevels_enabled }}"
  tags:
    - ctf1
    - ctfserver
    - ctflevels

- name: "Setting up CTF Level tasks"
  include: 'setupgame.yml'
  with_items:
    - "{{ ctfgame_userlevels_enabled }}"
  tags:
    - ctf1
    - ctfserver
    - ctflevels

- name: "Copy the tools.txt for Level 00"
  copy: src=levels/level00/tools.txt dest=/home/level00/tools.txt owner=root group=level00 mode=0440
  tags:
    - ctf1
    - ctfserver
    - ctflevels


- name: "Copy the syntax.txt for Level 00"
  copy: src=levels/level00/syntax.txt dest=/home/level00/syntax.txt owner=root group=level00 mode=0440
  tags:
    - ctf1
    - ctfserver
    - ctflevels

- name: "Copy the README for Level 00"
  copy: src=levels/level00/readme.txt dest=/home/level00/README owner=root group=level00 mode=0440
  tags:
    - ctf1
    - ctfserver
    - ctflevels
