---

### Binaries

- name: "Binary Level Setup | Copy the level C code for {{ item.name }}"
  copy:
    src: "levels/{{item.user}}/binary/{{item.user}}.c"
    dest: "/tmp/{{item.user}}.c"
    owner: root
    mode: 0644
  when: item.binary == True
  register: need_compile
  tags:
    - ctflevels
    - ctflevelcompile

- name: "Binary Level Setup | Copy the level C code for {{ item.name }}"
  when:
    - need_compile|succeeded
    - item.binary == True
  command: gcc -g -m32 -o /levels/{{item.user}}/{{item.user}} /tmp/{{item.user}}.c
# Might be useful to append to command at a later point
#creates=/levels/{{item.user}}/{{item.user}}
  tags:
    - ctflevels
    - ctflevelcompile

- name: "Binary Level Setup | Remove the level C code for {{ item.name }} from tmp"
  when:
    - need_compile|succeeded
    - item.binary == True
  command: rm -f /tmp/{{ item.user }}.c
  tags:
    - ctflevels
    - ctflevelcompile

- name: "Binary Level Setup | Ensures the compiled code for {{ item.name }} is in place with right access"
  when:
    - need_compile|succeeded
    - item.binary == True
  file:
    path: "/levels/{{ item.user }}/{{ item.user }}"
    mode: 4550
    owner: "{{item.suidowner}}"
    group: "{{item.user}}"
    state: file
  tags:
    - ctflevels
    - ctflevelcompile
