---

# NOTICE: Deprecated
- name: "Install print_with_env executable"
  copy: content="#!/usr/bin/bash\nperl -pe 's/\$(\w+)/$ENV{$1}/g' $1" dest=/usr/bin/print_with_env owner=root mode=0755
  tags:
    - ctf1
    - ctfserver
    - ctflevels

- name: Create levels directory
  file: path=/levels state=directory mode=0755
  tags:
    - ctf1
    - ctfserver
    - ctflevels

#
# user: level00 password: 89lka3ur9sd2
# user: level01 password: fYIAv1NfRvEwJMcVPyJX
# user: level02 password: 8Ja2HNPzRNbsJcUuc6uV
# user: level03 password: 64nBQaf0lAwthCXgHVci
# user: level04 password: lbJa9HZFkPyO7pNJGDNJ
#

- name: "Setting up CTF Levels"
  include: 'levelsetup.yml'
  with_items:
    - { name: "Level 00", user: "level00", pwclean: "89lka3ur9sd2", groups: "level00,{{default_ctfuser_group}}", password: "$6$RWc.Gc5LvtTTZ9vw$fQ2xxIaOUtuP6WkZd.CRfyRKeCALyBBYskIZR/eHjUdjnJvdhz.aONcYQdanfVJqBXX4wYE5huUm1M.wgUURg/" }
    - { name: "Level 01", user: "level01", pwclean: "fYIAv1NfRvEwJMcVPyJX", groups: "level00,level01,{{default_ctfuser_group}}", password: "$6$IIs.nwMlPioB38ge$V.L8M0hKSWu0a7FWpk3hUP7g0uN.gUYha8z2NyW3x.NKy4kIKNOo8VMN.dKo86au0xtruBJ6N.oCeYeuJTnpQ0" }
    - { name: "Level 02", user: "level02", pwclean: "8Ja2HNPzRNbsJcUuc6uV", groups: "level00,level01,level02,{{default_ctfuser_group}}", password: "$6$gnVQD5jXEvssG2IS$cocg/23RnDhgGpKMLODS.0LpqnSlPFFqFxBnCXasVU0uJZKywst5Dh5J13mK7/WDvLohZx7praHcda.ool0Fp/" }
    - { name: "Level 03", user: "level03", pwclean: "64nBQaf0lAwthCXgHVci", groups: "level00,level01,level02,level03,{{default_ctfuser_group}}", password: "$6$li5iFTDKRH1YEh6G$kBFtlEFHLQ2uSHapqhXAtzyWd.WgysogdwNJtATjp/K9Ld6.Qz4CmV6bEH.GhteZLU8vy1P5d10UPFk4zohFm0" }
    - { name: "Level 04", user: "level04", pwclean: "lbJa9HZFkPyO7pNJGDNJ", groups: "level00,level01,level02,level03,level04,{{default_ctfuser_group}}", password: "$6$PQrSxJGRpVLEvp59$9LWLgpsh4FffiT3XFLct.Zw2hp3SZsZAi8DbucQQbYKQWqlDVF1nPn5ptiL0fOA2f/HXueDewo2Jzud11GDyi0" }
  tags:
    - ctf1
    - ctfserver
    - ctflevels

- name: "Setting up CTF Level tasks"
  include: 'setuptasks.yml'
  with_items:
    - { name: "Level 00", user: "level00", suidowner: "level01" }
    - { name: "Level 01", user: "level01", suidowner: "level02" }
    - { name: "Level 02", user: "level02", suidowner: "level03" }
    - { name: "Level 03", user: "level03", suidowner: "level04" }
    - { name: "Level 04", user: "level04", suidowner: "level04" }
  tags:
    - ctf1
    - ctfserver
    - ctflevels

- name: "Copy the tools.txt for Level 00"
  copy: src=levels/level00/tools.txt dest=/home/level00/tools.txt owner=root mode=0440
  tags:
    - ctf1
    - ctfserver
    - ctflevels


- name: "Copy the syntax.txt for Level 00"
  copy: src=levels/level00/syntax.txt dest=/home/level00/syntax.txt owner=root mode=0440
  tags:
    - ctf1
    - ctfserver
    - ctflevels

- name: "Copy the README for Level 00"
  copy: src=levels/level00/readme.txt dest=/home/level00/README owner=root mode=0440
  tags:
    - ctf1
    - ctfserver
    - ctflevels
