---
# TODO: Find a better name for this file.. It don't self explain


### Binaries

- name: "Main Level Setup | Main level binaries"
  include: 'main_level_binaries.yml'
  register: levelbinaries_installed
  when:
    - item.binary == True
  tags:
    - ctfserver
    - ctflevels
    - ctflevelbinaries

### Services

- name: "Main Level Setup | Main level services"
  include: 'main_level_services.yml'
  register: levelservices_installed
  when:
    - item.service == True
  tags:
    - ctfserver
    - ctflevels
    - ctflevelservice
