---

- hosts: ctfservers
#- hosts: remotectftest
  gather_facts: true
  vars_files:
    - "../group_vars/all.yml"
    - "../group_vars/ctfserver.yml"
  roles:
    - { role: common, tags: ['common'] }
    - { role: aur, aur_package_name: vim-colorschemes, tags: ['aur'] }
    - { role: aur, aur_package_name: vim-colorsupport, tags: ['aur'] }
    - { role: aur, aur_package_name: vim-hexman, tags: ['aur'] }
    - { role: aur, aur_package_name: vim-markdown, tags: ['aur'] }
    - { role: aur, aur_package_name: jwasm, tags: ['aur'] }
    - { role: aur, aur_package_name: ipbt, tags: ['aur'] }
    - { role: aur, aur_package_name: termrec, tags: ['aur'] }
    - { role: aur, aur_package_name: ttyrec, tags: ['aur'] }
    - { role: aur, aur_package_name: aufs, tags: ['aur'] }
    - { role: aur, aur_package_name: linux-aufs_friendly, tags: ['aur'] }
    - { role: ctfserver, tags: ['ctfserver'] }
