---

- hosts: prod_ctfservers
#- hosts: remotectftest
  gather_facts: true
  vars_files:
    - "../group_vars/all.yml"
    - "../group_vars/ctfserver.yml"
  roles:
    - { role: common, tags: ['common'] }
    - { role: ctfserver, tags: ['ctfserver'] }
    - { role: webserver, tags: ['webserver'] }
