---

- name: Install ctfssh-wrapper.sh
  template: src=ctfssh-wrapper.sh.j2 dest=/usr/local/bin/ctfssh-wrapper.sh owner=root group=root mode=0755
  tags:
    - ctf1
    - ctfserver
    - ctfsecurity

- name: Copy the preconfigured sshd_config
  template: src=sshd_config.j2 dest=/etc/ssh/sshd_config owner=root group=root mode=0440
  notify: restart_sshd
  tags:
    - ctf1
    - ctfserver
    - ctfsecurity

