---


- name: "Adding group for {{ item.name }}"
  become: yes
  become_user: root
  group:
    name: "{{ item.user }}"
    state: present
  tags:
    - ctf1
    - ctfserver
    - ctflevels

- name: "Adding user for {{ item.name }}"
  become: yes
  become_user: root
  user:
    comment: "{{ item.name }}"
    name: "{{ item.user }}"
    password: "{{ item.password }}"
    state: present
    createhome: yes
    shell: /usr/bin/zsh
    update_password: always
    groups: "{{item.groups}},{{default_ctfuser_group}}"
    append: yes
  tags:
    - ctf1
    - ctfserver
    - ctflevels


- name: "Copy the motd.txt for {{ item.name }}"
  template: src=motd.txt.j2 dest=/home/{{item.user}}/motd.txt owner=root mode=0644
  tags:
    - ctf1
    - ctfserver
    - ctflevels

- name: "Setup the .passwd file for {{ item.name }}"
  copy: content={{item.pwclean}} dest=/home/{{item.user}}/.passwd owner=root mode=0644
  tags:
    - ctf1
    - ctfserver
    - ctflevels

- name: "Copy the .profile for {{ item.name }}"
  template: src=dotprofile.j2 dest=/home/{{item.user}}/.profile owner=root mode=0644
  tags:
    - ctf1
    - ctfserver
    - ctflevels

- name: "Copy the .template_story.txt for {{ item.name }}"
  ignore_errors: True
  template: src=levels/{{item.user}}/story.txt.j2 dest=/home/{{item.user}}/.template_story.txt owner=root mode=0644
  tags:
    - ctf1
    - ctfserver
    - ctflevels

- name: "Copy the recap.txt for {{ item.name }}"
  ignore_errors: True
  copy: src=levels/{{item.user}}/recap.txt dest=/home/{{item.user}}/recap.txt owner=root mode=0644
  tags:
    - ctf1
    - ctfserver
    - ctflevels


- name: "Copy the .zshrc for {{ item.name }}"
  template: src=dotzshrc.j2 dest=/home/{{item.user}}/.zshrc owner=root mode=0644
  tags:
    - ctf1
    - ctfserver
    - ctflevels


- name: "Copy the .bashrc for {{ item.name }}"
  template: src=dotbashrc.j2 dest=/home/{{item.user}}/.bashrc owner=root mode=0644
  tags:
    - ctf1
    - ctfserver
    - ctflevels
