---

- name: Create configuration directory for vim
  file:
    state: 'directory'
    dest: '/etc/vim'
    owner: 'root'
    group: 'root'
    mode: '0755'

- name: Configure vim global options
  template:
    src: 'vim/vimrc.local.j2'
    dest: '/etc/vim/vimrc.local'
    owner: 'root'
    group: 'root'
    mode: '0744'
